---
- name: Converge
  hosts: all

  tasks:
    - name: "Include bmillemathias.seaweedfs (without option)"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

    - name: Check master port is up and running
      wait_for:
        port: "{{ weed.master.port | int }}"
        timeout: 15
      retries: 3

    - name: reserve a volume id and a file id
      uri:
        url: "http://localhost:{{ weed.master.port }}/dir/assign"
      register: master_result

    - name: put some data in the volume server
      uri:
        url: "http://{{ master_result.json.url }}/{{ master_result.json.fid }}"
        status_code: [200, 201]
        method: POST
        body_format: form-multipart
        body:
          file: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/assets/ansible_logo.webp"
