---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
