---
name: Molecule Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_args: --all
